name: Binary

on: push

env:
  CARGO_TERM_COLOR: always

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install cross
        run: cargo install cross --git https://github.com/cross-rs/cross

      - name: Build
        run: |
          cross build --verbose --release --target=x86_64-unknown-linux-musl
          mv target/x86_64-unknown-linux-musl/release/client ./acmegen-token
          mv target/x86_64-unknown-linux-musl/release/server ./acmegen-server

      - uses: actions/upload-artifact@v3
        with:
          name: acmegen-token
          path: acmegen-token

      - uses: actions/upload-artifact@v3
        with:
          name: acmegen-server
          path: acmegen-server


      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            acmegen-token
            acmegen-server
